version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Mapeia a porta 8080 do host para a porta 80 do contêiner
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin.
      DB_NAME: magazord

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin.
      POSTGRES_DB: magazord

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80" # Mapeia a porta 5050 do host para a porta 80 do contêiner
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

networks:
  postgres-network:
    driver: bridge
